spring.application.name=trading-service

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=paper_trading
spring.datasource.password=paper123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

server.port =8082